# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51fd7e4e92745bc7caf2ccb113e2758a0aa7a7f05432c582850da9eb7746d308313442f76e635f7c0c97919cf42dcc6506612eab27f67e6d3768a89a888cd43e

test:
  secret_key_base: b7c95e0d4e298a1d527cffe5e49dd5c9b73a3b57a9af6ee138b45bc69c0ee3f013f9290063bcf334da637c75cbdbf59360353fed6cfae71c84f6ee505ef888f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
